controllers:
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 100
  robot_state_controller:
    type: robot_state_controller/RobotStateController
    publish_rate: 100

  arm_trajectory_controller:
    type: effort_controllers/JointTrajectoryController
    joints:
      - joint1
      - joint2
      - joint3
      - joint4
      - joint5
      - joint6
    gains:
      joint1: { p: 10000.0, i: 0.5, d: 300.0, i_clamp_max: 2, i_clamp_min: -2, antiwindup: true, publish_state: false }
      joint2: { p: 17000, i: 0.5, d: 1000.0, i_clamp_max: 1, i_clamp_min: -1, antiwindup: true, publish_state: false }
      joint3: { p: 9000.0, i: 0.5, d: 220.0, i_clamp_max: 2, i_clamp_min: -2, antiwindup: true, publish_state: false }
      joint4: { p: 250.0, i: 0.5, d: 2, i_clamp_max: 1, i_clamp_min: -1, antiwindup: true, publish_state: false }
      joint5: { p: 50.0, i: 0.5, d: 2.0, i_clamp_max: 1, i_clamp_min: -1, antiwindup: true, publish_state: false }
      joint6: { p: 150.0, i: 0.5, d: 1.4, i_clamp_max: 1, i_clamp_min: -1, antiwindup: true, publish_state: false }
#    constraints:
#      joint1: { trajectory: 0.03, goal: 0.01 }
#      joint2: { trajectory: 0.03, goal: 0.01 }
#      joint3: { trajectory: 0.03, goal: 0.01 }
#      joint4: { trajectory: 0.03, goal: 0.015 }
#      joint5: { trajectory: 0.05, goal: 0.03 }
#      joint6: { trajectory: 0.03, goal: 0.01 }

  chassis_controller:
    type: rm_chassis_controllers/OmniController
    # ChassisBase
    publish_rate: 100
    enable_odom_tf: true
    publish_odom_tf: true
    power:
      effort_coeff: 2.0
      vel_coeff: 0.008
      power_offset: -9.8
    twist_angular: 0.5233
    timeout: 0.1
    pid_follow: { p: 4.0, i: 0, d: 0.02, i_max: 0.0, i_min: 0.0, antiwindup: true, publish_state: false }
    twist_covariance_diagonal: [ 0.001, 0.001, 0.001, 0.001, 0.001, 0.001 ]
    max_odom_vel: 10.0
    # OmniController
    wheels:
      left_front:
        pose: [ 0.213, 0.1945, 0. ]
        roller_angle: -0.785
        joint: left_front_wheel_joint
        <<: &wheel_setting
          radius: 0.07
          pid: { p: 0.4, i: 0, d: 0.0, i_max: 0.0, i_min: 0.0, antiwindup: true, publish_state: false }
      right_front:
        pose: [ 0.213, -0.1945, 0. ]
        roller_angle: 0.785
        joint: right_front_wheel_joint
        <<: *wheel_setting
      left_back:
        pose: [ -0.213, 0.1945, 0. ]
        roller_angle: 0.785
        joint: left_back_wheel_joint
        <<: *wheel_setting
      right_back:
        pose: [ -0.213, -0.1945, 0. ]
        roller_angle: -0.785
        joint: right_back_wheel_joint
        <<: *wheel_setting


  gimbal_controller:
    type: rm_gimbal_controllers/Controller
    yaw:
      joint: "yaw_joint"
      pid: { p: 0.5, i: 0, d: 0.0, i_clamp_max: 0.0, i_clamp_min: -0.0, antiwindup: true, publish_state: false }
    pitch:
      joint: "pitch_joint"
      pid: { p: 0., i: 0.0, d: 0.0, i_clamp_max: 0.0, i_clamp_min: -0.0, antiwindup: true, publish_state: false }
    feedforward:
      gravity: 0.0
      enable_gravity_compensation: false
      mass_origin: [ 0.0,0.0,0.0 ]
    bullet_solver:
      resistance_coff_qd_10: 0.45
      resistance_coff_qd_15: 1.0
      resistance_coff_qd_16: 0.7
      resistance_coff_qd_18: 0.55
      resistance_coff_qd_30: 3.0
      g: 9.81
      delay: 0.1
      dt: 0.001
      timeout: 0.001
      publish_rate: 50

  gpio_controller:
    type: gpio_controller/Controller
    gpios: [ "gripper" ]



  ######################### Calibration Controllers ######################


  gimbal_lifter_calibration_controller:
    type: rm_calibration_controllers/MechanicalCalibrationController
    actuator: [ gimbal_lifter_joint_motor ]
    velocity:
      search_velocity: -1.5
      vel_threshold: 0.01
      joint: gimbal_lifter_joint
      pid: { p: 5, i: 0, d: 1, i_clamp_max: 0.0, i_clamp_min: 0.0, antiwindup: true, publish_state: false }



  joint1_calibration_controller:
    type: rm_calibration_controllers/MechanicalCalibrationController
    actuator: [ joint1_motor ]
    velocity:
      search_velocity: -0.6
      vel_threshold: 0.001
      joint: joint1
      pid: { p: 100, i: 0, d: 0.0, i_clamp_max: 0.0, i_clamp_min: 0.0, antiwindup: true, publish_state: false }
