controllers:
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 100
  robot_state_controller:
    type: robot_state_controller/RobotStateController
    publish_rate: 100

  leg_rf_calibration_controller:
    type: rm_calibration_controllers/MechanicalCalibrationController
    actuator: [ right_front_leg_joint_motor ]
    velocity:
      joint: right_front_first_leg_joint
      search_velocity: -1.4
      vel_threshold: 0.05
      pid: { p: 2.0, i: 0, d: 0.0, i_clamp_max: 0.0, i_clamp_min: 0.0, antiwindup: true }

  leg_lf_calibration_controller:
    type: rm_calibration_controllers/MechanicalCalibrationController
    actuator: [ left_front_leg_joint_motor ]
    velocity:
      joint: left_front_first_leg_joint
      search_velocity: -1.4
      vel_threshold: 0.05
      pid: { p: 2.0, i: 0, d: 0.0, i_clamp_max: 0.0, i_clamp_min: 0.0, antiwindup: true }

  leg_lb_calibration_controller:
    type: rm_calibration_controllers/MechanicalCalibrationController
    actuator: [ left_back_leg_joint_motor ]
    velocity:
      joint: left_back_first_leg_joint
      search_velocity: 1.4
      vel_threshold: 0.05
      pid: { p: 2.0, i: 0, d: 0.0, i_clamp_max: 0.0, i_clamp_min: 0.0, antiwindup: true }

  leg_rb_calibration_controller:
    type: rm_calibration_controllers/MechanicalCalibrationController
    actuator: [ right_back_leg_joint_motor ]
    velocity:
      joint: right_back_first_leg_joint
      search_velocity: 1.4
      vel_threshold: 0.05
      pid: { p: 2.0, i: 0, d: 0.0, i_clamp_max: 0.0, i_clamp_min: 0.0, antiwindup: true }

  four_link_vmc_controller:
    type: rm/VMCController
    left_joint: right_front_first_leg_joint
    right_joint: right_back_first_leg_joint
    vmc_bias_angle: 3.49
    pid_angle: { p: 30, i: 0, d: 2, i_max: 0.0, i_min: 0.0, antiwindup: true, publish_state: true }
    pid_length: { p: 400.0, i: 2, d: 20, i_clamp_max: 40.0, i_clamp_min: -40.0, antiwindup: true, publish_state: true }

  legged_balance_controller:
    type: rm/LeggedBalanceController
    left_wheel:
      joint: left_wheel_joint
      pid: { p: 0.6, i: 0, d: 0.0, i_max: 0.0, i_min: 0.0, antiwindup: true, publish_state: true }
    right_wheel:
      joint: right_wheel_joint
      pid: { p: 0.6, i: 0, d: 0.0, i_max: 0.0, i_min: 0.0, antiwindup: true, publish_state: true }
    pid_follow: { p: 7.0, i: 0, d: 0.3, i_max: 0.0, i_min: 0.0, antiwindup: true, publish_state: true }
    pid_left_leg: { p: 300.0, i: 9, d: 20, i_clamp_max: 20.0, i_clamp_min: -20.0, antiwindup: true, publish_state: true }
    pid_right_leg: { p: 300.0, i: 9, d: 20, i_clamp_max: 20.0, i_clamp_min: -20.0, antiwindup: true, publish_state: true }
    pid_theta_diff: { p: 20.0, i: 0.0, d: 0.01, i_max: 0.0, i_min: 0.0, antiwindup: true, publish_state: true }
    pid_roll: { p: 300.0, i: 8, d: 5, i_clamp_max: 10.0, i_clamp_min: -10.0, antiwindup: true, publish_state: true }
    pid_center_gravity: { p: 0.0, i: 600, d: 0, i_clamp_max: 0.4, i_clamp_min: -0.4, antiwindup: true, publish_state: true }
    pid_length_diff: { p: 30.0, i: 0, d: 0, i_clamp_max: 0.0, i_clamp_min: -0.0, antiwindup: true, publish_state: true }
    leg_protect_angle: 0.9  #0.9
    pitch_protect_angle: 1.1 #1.1
    roll_protect_angle: 1.0
    leg_protect_length: 0.1
    ground_support_threshold: 5
    vmc_bias_angle: 3.49

    gravity_compensation_vel_threshold: 0.1
    gravity_compensation_pos_threshold: 0.5

    jump_over_time: 2.0
    p1: -241100
    p2: 170300
    p3: 39310
    p4: 3234