rm_track:
  filters:
    - type: height_filter
      basic_range: [ -0.6, 2.0 ]
      double_check_range: [ 0.5, 1.0 ]
    - type: distance_filter
      basic_range: [ 0., 5. ]
      double_check_range: [ 4.0, 6.0 ]
  selectors:
    - last_armor
    - same_id_armor
    - random_armor
  buffer:
    max_match_distance: 0.1
    max_storage_time: 2.0
    max_lost_time: 0.1
    linear_kf:
      Q: [ 1000.0, 1000.0, 1000.0, 1000.0, 1000.0, 1000.0 ]
      R: [ 1, 1, 1 ]
