rm_manual:
  robot_type: "balance"
  chassis_calibrate_motor: [ ]
  gimbal_calibrate_motor: [ "pitch_joint_motor" ,"left_momentum_block_joint_motor", "right_momentum_block_joint_motor" ]
  shooter_calibrate_motor: [ "cover_joint_motor", "trigger_joint_motor" ]
  flank_frame: "flank_frame"
  reverse_frame: "yaw_reverse_frame"
  supply_frame: "yaw"
  chassis:
    topic: "/controllers/chassis_controller/command"
    accel_x:
      - [ 60.0, 1.0 ]
      - [ 80.0, 2.0 ]
      - [ 100.0, 4.0 ]
    accel_y:
      - [ 60.0,4.0 ]
    accel_z:
      - [ 60.0,3.0 ]
      - [ 80.0,5.0 ]
      - [ 100.0,8.0 ]
    safety_power: 80
    capacitor_threshold: 0.1
    charge_power: 20
    extra_power: 120
    burst_power: 200
    buffer_threshold: 10
    power_gain: 0.9
  balance:
    topic: "/controllers/chassis_controller/mode"
  vel:
    topic: "/cmd_vel"
    power_limit_topic: "/rm_referee/game_robot_status"
    chassis_power_limit_topic: "/controllers/chassis_controller/command"
    max_linear_x:
      - [ 60.0,1.30 ]
      - [ 80.0,2.00 ]
      - [ 100.0,3.00 ]
      - [ 240.0, 3.50 ]
    max_linear_y:
      - [ 60.0,1.0 ]
    max_angular_z:
      - [ 60.0,10.1 ]
      - [ 80.0,13.0 ]
      - [ 240.0,18.4 ]
    gyro_move_reduction: 0.3
    gyro_rotate_reduction: 0.7
  gimbal:
    topic: "/controllers/gimbal_controller/command"
    max_yaw_vel: 12.56
    max_pitch_vel: 8.37
    track_timeout: 0.5
    target_cost_function:
      k_pos: 1.0
      k_vel: 1.0
      k_hp: 1.0
      k_freq: 1.0
      timeout: 0.05
  shooter:
    topic: "/controllers/shooter_controller/command"
    gimbal_error_tolerance: 0.15
    target_acceleration_tolerance: 0.9
    speed_10m_per_speed: 10.0
    speed_15m_per_speed: 28.0
    speed_16m_per_speed: 16.0
    speed_18m_per_speed: 15.72
    speed_30m_per_speed: 28.0
    heat_limit:
      low_shoot_frequency: 20
      high_shoot_frequency: 20
      burst_shoot_frequency: 20
      safe_shoot_frequency: 3
      heat_coeff: 8.0
      type: "ID1_17MM"
  cover:
    topic: "/controllers/cover_controller/command"
    on_pos: 1.618
    off_pos: 0.04
  detection_switch:
    fail_limit: 10
    service_name: "/Processor/status_switch"

  controllers_list:
    state_controllers:
      - controllers/joint_state_controller
      - controllers/robot_state_controller
    main_controllers:
      - controllers/chassis_controller
      - controllers/orientation_controller
      - controllers/gimbal_controller
      - controllers/shooter_controller
      - controllers/cover_controller
    calibration_controllers:
      - controllers/gimbal_calibration_controller
      - controllers/left_momentum_block_calibration_controller
      - controllers/right_momentum_block_calibration_controller
      - controllers/trigger_calibration_controller
      - controllers/cover_calibration_controller

  gimbal_calibration:
    - start_controllers:
        - controllers/gimbal_calibration_controller
        - controllers/cover_calibration_controller
        - controllers/left_momentum_block_calibration_controller
        - controllers/right_momentum_block_calibration_controller
      stop_controllers:
        - controllers/gimbal_controller
        - controllers/cover_controller
        - controllers/chassis_controller
      services_name:
        - /controllers/gimbal_calibration_controller/is_calibrated
        - /controllers/cover_calibration_controller/is_calibrated
        - controllers/left_momentum_block_calibration_controller/is_calibrated
        - controllers/right_momentum_block_calibration_controller/is_calibrated
  shooter_calibration:
    - start_controllers:
        - controllers/trigger_calibration_controller
      stop_controllers:
        - controllers/shooter_controller
      services_name:
        - /controllers/trigger_calibration_controller/is_calibrated

controllers:
  cover_controller:
    type: effort_controllers/JointPositionController
    joint: "cover_joint"
    pid: { p: 15.0, i: 0.0, d: 1.2, i_clamp_max: 0.0, i_clamp_min: 0.0, antiwindup: true, publish_state: true }
